// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Interview challenge
//
//	Implementation for the interview challenge
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0
//	Contact:
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
