// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HandlerRootResponse handler root response
//
// swagger:model handler.RootResponse
type HandlerRootResponse struct {

	// date
	Date int64 `json:"date,omitempty"`

	// kubernetes
	Kubernetes bool `json:"kubernetes,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this handler root response
func (m *HandlerRootResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this handler root response based on context it is used
func (m *HandlerRootResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlerRootResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlerRootResponse) UnmarshalBinary(b []byte) error {
	var res HandlerRootResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
