// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HandlerValidateIPResponse handler validate IP response
//
// swagger:model handler.ValidateIPResponse
type HandlerValidateIPResponse struct {

	// status
	Status *bool `json:"status,omitempty"`
}

// Validate validates this handler validate IP response
func (m *HandlerValidateIPResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this handler validate IP response based on context it is used
func (m *HandlerValidateIPResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlerValidateIPResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlerValidateIPResponse) UnmarshalBinary(b []byte) error {
	var res HandlerValidateIPResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
