// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelAddress model address
//
// swagger:model model.Address
type ModelAddress struct {

	// ip
	IP string `json:"ip,omitempty"`
}

// Validate validates this model address
func (m *ModelAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model address based on context it is used
func (m *ModelAddress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelAddress) UnmarshalBinary(b []byte) error {
	var res ModelAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
